### ISSUE TITLE
Two requests are required to log in via API

### ISSUE THREAD

**Issue by nandomindway** [dneustadt/DneustadtCsrfCookieBundle#1]
Hello there! This is my first issue.  We are developing an API for a mobile app and we are working in the json_login with symfony 5.1.5 and we have implemented this bundle to give CSRF Protection to the app. The problem is that we have to make two requests to the json_login route to get XSRF Cookie and log in.
Is there anyway to solve this problem????
I enclose  a screenshot of my code
`/**
     * @Route("/json_login", name="json_login", methods={"POST"}, defaults={"csrf": {"create": true}})
     * @param IriConverterInterface $iriConverter
     * @param TokenStorageInterface $tokenStorage
     * @param Request $request
     * @return Response
     */
    public function jsonLoginAction(IriConverterInterface $iriConverter, TokenStorageInterface $tokenStorage, Request $request)
    {

        if(!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            return $this->json([
                'error' => 'Invalid Request!!!'
            ], 400);
        }

         $response = $this->json([
            'user' => $iriConverter->getIriFromItem($this->getUser())
        ]);

        return new JsonResponse($response->getContent(), 201);
    }

`
That's my json_login code

`dneustadt_csrf_cookie:
   Generally enable/disable the CSRF protection
  enable: true
   ID used to generate token
  id: csrf
   Name of the cookie the token is stored in
  name: XSRF-TOKEN
  Cookie expiration
  expire: 0
  Cookie path
  path: /
   Cookie domain
  domain: *****************
  Cookie secure
  secure: false
  Name of the HTTP header the token is expected to be stored in
  header: X-XSRF-TOKEN
   Cookie same site policy
  sameSite: lax`

And that's my configuration

**Comment by dneustadt** [comment]
Hi,
if your login endpoint requires a CSRF token then the token has to be present client-side **before** the first request to the login endpoint. That is intended behaviour. The usual solution to that problem involves having a dedicated endpoint to retrieve an initial CSRF token before any further requests. So whenever you load your login form initially you request said endpoint to get a CSRF token first. Then you allow the user to enter his credentials and the request to the login endpoint can include a CSRF token.
