### ISSUE TITLE
support symfony 6

### ISSUE THREAD

**Issue by ZFnine0010** [dneustadt/DneustadtCsrfCookieBundle#6]
Hello, first i would like to thank you so much for providing this package

it seems like this package is only for symfony ^5.x
when i tried to install via composer i got this message:
```bash
Problem 1
    - Root composer.json requires dneustadt/csrf-cookie-bundle ^1.0 -> satisfiable by dneustadt/csrf-cookie-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - dneustadt/csrf-cookie-bundle[1.0.0, ..., 1.0.3] require symfony/config ^5.0 -> found symfony/config[v5.0.0, ..., v5.4.9] but the package is fixed to v6.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```
BR

**Comment by koz1ma** [comment]
I had the same issue

**Comment by dneustadt** [comment]
It took a while 🙈 Until now I was still locked at Symfony 5 but now I got around to update and also tested this bundle. I don't use it in production anymore so it fell to the wayside. Looking good though, no breaking changes as far as I could see, allowed `^6.0`, should work fine.
